### PR TITLE
Make MutationObserver disconnect while links are being processed, then observe again.

### PR DESCRIPTION
**Pull request by lewisje**
The key problem is that while the links are being processed, some aspects of the DOM that the `MutationObserver` observes will be changed, causing the callback to fire yet again, leading to an avalanche of function calls (even worse, the callback does DOM-manipulating work for *any* mutation, even something that isn't related to adding or changing links); a better idea is to disconnect the observer, then look through the recorded DOM mutations for anything of interest (specifically, added links or changed `href`s) before deciding whether to process the links on the page, and finally, whether re-processing or not, making the observer observe again.

### CODE REVIEW

**Comment by selfagency** [comment]
@lewisje So I'm trying to merge this into the Chrome plugin and I'm hitting a wall. Check out the latest push to the development branch in the chrome/js/bs-detector.js file. I'm getting: `jquery-3.1.1.slim.min.js:2 jQuery.Deferred exception: b.toLowerCase is not a function TypeError: b.toLowerCase is not a function` executing that code.

**Comment by lewisje** [comment]
...I thought I actually was working off the Chrome extension.

**Comment by lewisje** [comment]
I found one problem that [JSHint](http://jshint.com/) was able to find, and another that it wasn't.

First, you had a line that said `if (siteId = 'facebook') {` and you'd need `if (siteId == 'facebook') {`; triple-equals would be even better, but the point is that you probably didn't intend for `siteId` to be *set to* `'facebook'`.

Next, in the `getHost` function, you had a line that said `if ($(thisElement).attr('data-expanded-url' != null)) {`, and it should say `if ($(thisElement).attr('data-expanded-url') != null) {`; as you have it, the expression `'data-expanded-url' != null` is always `true`, and then it tries to set the attribute `true` to `undefined`, but it expects a string as the first argument to the `.attr` method, so it throws an error when it tries to call `true.toLowerCase()`.

I'll test out the dev branch some more and send in a PR for it.

**Comment by selfagency** [comment]
this is what happens when i code after midnight

**Pull request merged**
