### PR TITLE
Data update (New York Post)

### PR DESCRIPTION
**Pull request by tomatell**
- added nypost.com for the following reason.
The following article is not true.
http://nypost.com/2016/11/25/corona-founder-dies-makes-his-entire-villag
e-millionaires/

### CODE REVIEW

**Comment by BigMcLargeHuge** [comment]
I agree that the NY Post is (at least) highly suspect but is falsehood a chronic condition for them?  We need to be cautious in taking on mainstream sources because (right or wrong) it may serve to marginalize our own credibility rather than the other way around.

**Comment by tomatell** [comment]
True. Perhaps, we should contact NYP to let them know the information is false?

**Comment by Bastlynn** [comment]
Probably the best approach yes. Even legit reporters can have a bad day. So this is exactly what letters to the editor and/or corrections are for. I'm not seeing contact for an ombudsman for the NYP  on their site, but there is contact info for editors.

**Comment by tomatell** [comment]
Alright then. Should I contact them. At the moment, my hands are full.

**Comment by tomatell** [comment]
I have contacted NYP.
Let's see their response.

**Pull request closed without merging**
